### PR TITLE
Fix deepcache for svd

### PR DESCRIPTION
**Pull request by lixiang007666**
## ComfyUI Node and Example

Node name:

- ModuleDeepCacheSpeedup
- SVDSpeedup

Example workflow: 

svd-deepcache-onediff

## Depending on the new oneflow community edition

cuda 11.8: `python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu118`

cuda12.1: `python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu121`

cuda12.2: `python3 -m pip install --pre oneflow -f https://oneflow-pro.oss-cn-beijing.aliyuncs.com/branch/community/cu122`

### A800-SXM4-80GB

- Size: 1024 * 576 * 25

| SVD with Pytorch | SVD Speedup with OneDiff | SVD DeepCache Speedup with OneDiff |
| :--------------: | :----------------------: | :--------------------------------: |
|  0.65 it/s (1x)  |    1.00 it/s (1.54x)    |         1.54 it/s (2.37x)         |

The above tests are based on the community version of OneFlow.

## Result
fig-svd

When using the SVDSpeedup node of onediff, the video quality is lossless. When using the ModuleDeepCacheSpeedup node, there is a slight loss in quality, but the speed increases by more than double.

Thanks to @Dango233 from Stability AI. He inspired us to try our acceleration node(DeepCache with OneDiff compilation) on SVD.

### CODE REVIEW

**Comment by yuanms2** [comment]
不加onediff， PyTorch SVD + DeepCache的效果怎样

**Comment by lixiang007666** [comment]
> 不加onediff， PyTorch SVD + DeepCache的效果怎样

我后面本地看下。

**Comment by lixiang007666** [comment]
issue comment 更新了。

**Review by strint — APPROVED** [review]

**Comment by nyukers** [comment]
Can I use onediif for CogVideo workflows?

**Comment by nyukers** [comment]
Ok, is it working under Windows?

**Pull request merged**
